"""Skill taxonomy -- canonical skill names with alias normalization.

RE-EXPORT SHIM. The implementation moved to the ``jobcore`` package
(``mcp-servers/jobcore``) so a second job server can share it; a skill alias
table is true on every board, so keeping two copies would guarantee drift.

Every import path that worked before still works:

    from naukri_server.domain.skill_taxonomy import SKILL_ALIASES, SkillTaxonomy, DEFAULT_TAXONOMY

To add a Naukri-only skill, do NOT edit this file — add it to
``jobcore/src/jobcore/skills.py`` if it is universal, or build a local
taxonomy with ``DEFAULT_TAXONOMY.extended({...})`` if it truly is not.
"""

from jobcore.skills import (
    DEFAULT_TAXONOMY,
    SKILL_ALIASES,
    SkillTaxonomy,
)

__all__ = ["SKILL_ALIASES", "SkillTaxonomy", "DEFAULT_TAXONOMY"]
